services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    command: npm start
    volumes:
      - ./backend/src/:/app/src/

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    command: sh -c "while ! nc -z backend 4000; do sleep 1; done && npm run dev"
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/app/src/
