name: front_ui_test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  front-ui-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run interface test
        run: cd frontend && npm ci && npm run test
